version: "3.7"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_net
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
    container_name: email-canal-zookeeper

  kafka:
    image: bitnami/kafka:2.6.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://127.0.0.1:9093,CLIENT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_MESSAGE_MAX_BYTES=104857600
    depends_on:
      - zookeeper
    networks:
      - kafka_net
    volumes:
      - kafka_data:/bitnami/kafka/data
    container_name: email-canal-kafka

  redis:
    image: bitnami/redis:6.2.7
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
    container_name: email-canal-redis

networks:
  kafka_net:

volumes:
  kafka_data:
  zookeeper_data:
  redis_data:
