version: "3.7"
services:
  email-canal:
    image: k8scat/email-canal:latest
    volumes:
      - email-canal-attachments:/email-canal/data/attachments
      - ./settings.py:/opt/email-canal/settings.py
      - ./data/pop3_index.txt:/email-canal/data/pop3_index.txt
    networks:
      - kafka_net
    restart: always
    container_name: email-canal

volumes:
  email-canal-attachments:
    name: email-canal-attachments

networks:
  kafka_net:
    external: true
