version: "3.7"
services:
  email-canal:
    image: k8scat/email-canal:latest
    volumes:
      - ./data/attachments:/email-canal/data/attachments
      - ./settings.py:/opt/email-canal/canal/settings.py
      - ./data/pop3_index.txt:/email-canal/data/pop3_index.txt
      - ./logs:/email-canal/logs
    networks:
      - kafka_net
    restart: always
    container_name: email-canal

networks:
  kafka_net:
    external: true
